### ISSUE TITLE
构建镜像出错

### ISSUE THREAD

**Issue by kawa23** [osswangxining/Istio-TCPRoute-Sample#1]
你好，`docker build -t registry.cn-hangzhou.aliyuncs.com/wangxining/tcptest:0.1 .` 构建镜像时报错，

`
Sending build context to Docker daemon  78.34kB
Step 1/10 : FROM golang:latest AS builder
 ---> 00d970a31ef2
Step 2/10 : RUN mkdir -p /go/src/github.com/osswangxining/go-echo
 ---> Using cache
 ---> cdd6f058352e
Step 3/10 : COPY . /go/src/github.com/osswangxining/go-echo
 ---> Using cache
 ---> 280715cd7802
Step 4/10 : RUN go get ...
 ---> Using cache
 ---> 925b5c97ed87
Step 5/10 : RUN CGO_ENABLED=0 go build -a -installsuffix cgo -o /go/bin/tcp-echo ./src/github.com/osswangxining/go-echo
 ---> Using cache
 ---> b9f565934f91
Step 6/10 : FROM alpine:latest
 ---> a24bb4013296
Step 7/10 : RUN apk --no-cache add ca-certificates
 ---> Running in 57aab49be5ca
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
ERROR: unsatisfiable constraints:
  ca-certificates (missing):
    required by: world[ca-certificates]
The command '/bin/sh -c apk --no-cache add ca-certificates' returned a non-zero code: 1
`

---
`registry.cn-hangzhou.aliyuncs.com/wangxining/tcptest:0.1`作者构建好的镜像是放在阿里云私人仓库吗，我 `pull` 时要登录，拉不了

**Comment by osswangxining** [comment]
docker build -t <registry.cn-hangzhou.aliyuncs.com/wangxining/tcptest:0.1> . 构建镜像的命令中的<registry.cn-hangzhou.aliyuncs.com/wangxining/tcptest:0.1> 是示例镜像名称
需要替换自己的镜像仓库及名称

**Comment by kawa23** [comment]
> docker build -t <registry.cn-hangzhou.aliyuncs.com/wangxining/tcptest:0.1> . 构建镜像的命令中的<registry.cn-hangzhou.aliyuncs.com/wangxining/tcptest:0.1> 是示例镜像名称
> 需要替换自己的镜像仓库及名称

@osswangxining 感谢回复，我实际用的命令是` docker build -t tcptest:0.1 .`，构建失败报的这个错，我是在自己机子`Ubuntu 18.04.4 LTS`上构建的，`tcptest:0.1`这个只是个名称而已吧，只要命名规范就行，会不会是 `Dockerfile`中的所用的基础镜像都是最新的导致，因为用的是`golang:latest` 和  `alpine:latest`，但是我尝试用旧的版本也不行~，作者可以把你构建好的镜像开源吗
